database:
  typedb: postgres
  dbname: financial_data
  user: postgres
  password: postgres
  host: localhost
  port: 5432
tables:
  - name: test_decimal
    schema: public
  - name: test_max_length
    schema: public


